### ISSUE TITLE
Read the docs links dont work

### ISSUE THREAD

**Issue by Sh4zKh4n** [shervinazadi/topoGenesis#2]
When I try to go and look at the read the docs and click one of the contents. I have a time out error. So can't really evaluate the library.

**Comment by shervinazadi** [comment]
Do you mean inside the documentation on [readthedocs](https://topogenesis.readthedocs.io) or when you build the documentation locally? Can you please specify an example of a broken link?

**Comment by Sh4zKh4n** [comment]
@shervinazadi  seems the links are working now. yes I meant readthedocs from the link https://topogenesis.readthedocs.io/  not locally built. When I tried to click on anything in the menu bar it just timed out. Tried it for a while but I have checked this morning and its working. Weird but who cares it's up and running! So I will close this issue! Thanks for waving a magic want to fix!
